### ISSUE TITLE
utop: segfault, matrices not printing

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#110]
Maybe these are different problems, but they're appearing at the same time; I just pulled the latest master this evening.  I get a segfault or another memory error from `reverse` in utop sometimes.  I'm not sure what else causes it.  Also, matrices are not printing out their contents in utop, even though I am running `#require "owl_zoo"`.  These problems aren't occurring with a version of Owl from a day or two ago.
```ocaml
# let k = M.sequential 1 51;;
val k : M.mat = <abstr>
# M.reverse k;;
- : M.mat = <abstr>
ocamlrun(88974,0x7fff73eca000) malloc: *** error for object 0x7fcd087c1d78: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
/Users/marshall/bin/itop: line 2: 88974 Abort trap: 6           utop `find _build/default -name '*.cma' | sed -e 's/[.a-zA-Z]*$//' -e 's/^/-I /'` "$@"
```
(`itop` is just `utop` run from a script with some extra `-I` flags.)
```ocaml
let k = M.sequential 1 51;;
val k : M.mat = <abstr>
# let xs = M.concat_vertical k k;;
val xs : M.mat = <abstr>
# let xs = M.concat_vertical k (M.reverse k);;
/Users/marshall/bin/itop: line 2: 88962 Segmentation fault: 11  utop `find _build/default -name '*.cma' | sed -e 's/[.a-zA-Z]*$//' -e 's/^/-I /'` "$@"
```

I would rather have had a chance to do more investigation before reporting this, but it seems serious enough that I felt I should report it right away.

One thing that's different in my config is that I add `-L/usr/local/opt/openblas/lib` to src/owl/jbuild, following earlier advice for MacOS.  I'm also using 4.05.0+flambda, though I don't add any `-O` flags or anything else to the Owl jbuild files other than that `-L`.  I can try vanilla 4.05.0 in the morning if that seems helpful, roll back to earlier versions and see where the problems are introduced, etc.
```
utop -version
The universal toplevel for OCaml, version 2.0.1, compiled for OCaml version 4.05.0
```

**Comment by jzstark** [comment]
I get similar error message on my machine using the latest master branch code:

```
utop # Mat.reverse k;;
- : Mat.mat = <abstr>                                                                                
*** Error in `/usr/bin/ocamlrun': double free or corruption (out): 0x0000000001ba9f70 ***            
======= Backtrace: =========                                                                         
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f72ea78d7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f72ea79637a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f72ea79a53c]
/usr/bin/ocamlrun(caml_empty_minor_heap+0x116)[0x40ec96]
/usr/bin/ocamlrun(caml_gc_dispatch+0x46)[0x40f106]
/usr/bin/ocamlrun(caml_make_vect+0x10c)[0x416e4c]
/usr/bin/ocamlrun(caml_interprete+0x13cb)[0x4276db]
/usr/bin/ocamlrun(caml_main+0x1e8)[0x4296d8]
/usr/bin/ocamlrun(main+0xc)[0x40ca2c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f72ea736830]
/usr/bin/ocamlrun(_start+0x29)[0x40ca69]
======= Memory map: ========
00400000-00437000 r-xp 00000000 103:05 527937                            /usr/bin/ocamlrun
00636000-00637000 r--p 00036000 103:05 527937                            /usr/bin/ocamlrun
00637000-00639000 rw-p 00037000 103:05 527937                            /usr/bin/ocamlrun
...
7f72e9e7b000-7f72e9e7c000 r--p 0000e000 103:05 802480              /usr/lib/ocaml/stublibs/dllunix.so
Aborted (core dumped)
```
I was trying to change the shape of the matrix or generate  matrix with `Mat.zeros` but the same error still occur.

```
utop -version
The universal toplevel for OCaml, version 2.0.1, compiled for OCaml version 4.04.2
```

**Comment by ryanrhymes** [comment]
Thank for reporting this. This relates to my last night's update on simplifying the types in owl_dense_common. I implemented a new owl_copy function with slightly different semantics. This should have been fixed now, please give it a try.

There are also several other places called owl_copy, I will check them all later today. But in case you noticed anything wrong, please do let me know, many thanks!

**Comment by mars0i** [comment]
Thanks very much; I've experienced no memory problems so far with the new commit.

Matrices are still not printing out, so that seems to be a different problem.  In utop:
```ocaml
# #require "owl_zoo";;
# M.sequential 1 8;;
- : M.mat = <abstr>
#
```

**Comment by ryanrhymes** [comment]
@mars0i my apologies, I replied here last night: https://github.com/ryanrhymes/owl/issues/99

In short, 
```ocaml
#require "owl_top";;
```

**Comment by mars0i** [comment]
Ah, OK, great.  For some reason I didn't get a notification for that.
